---
- name: Install PostgreSQL
  become: True
  apt:
    name:
      - "postgresql-{{ postgres_version }}"
      - "postgresql-client-{{ postgres_version }}"
      - "postgresql-contrib-{{ postgres_version }}"
      - python-psycopg2


- name: Configure PostgreSQL
  become: True
  template:
    src: "{{ item }}.j2"
    dest: "/etc/postgresql/{{ postgres_version }}/main/{{ item }}"
    owner: "{{ postgres_user }}"
    group: "{{ postgres_user }}"
    mode: 0640
  with_items:
    - pg_hba.conf
    - postgresql.conf
  notify:restart postgres
